# Copyright 2026 Nicholas Salois.
#
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file in the repository root for the full license.

[toolchain]
channel = "1.96.1"
components = ["rustfmt", "clippy"]
targets = ["thumbv7em-none-eabihf"]
