use opta_buchi::Endpoint;
use opta_gateway_contracts::namespace::{Access, ValueKind};

pub const PROCESS_NODE_COUNT: usize = 29;
pub const SETTINGS_NODE_COUNT: usize = 21;
pub const INFO_NODE_COUNT: usize = 36;
pub const SETTINGS_NODE_OFFSET: usize = PROCESS_NODE_COUNT;
pub const INFO_NODE_OFFSET: usize = PROCESS_NODE_COUNT + SETTINGS_NODE_COUNT;
pub const NODE_COUNT: usize = PROCESS_NODE_COUNT + SETTINGS_NODE_COUNT + INFO_NODE_COUNT;

#[repr(usize)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RuntimeNode {
    ProcessState = 0,
    ProcessHeatingSet,
    ProcessBathTemperature,
    ProcessHeatingRunning,
    ProcessCoolingSet,
    ProcessCoolingActual,
    ProcessCoolingRunning,
    ProcessVacuumSet,
    ProcessRotationSpeed,
    ProcessPressure,
    ProcessVacuumAerateValveOpen,
    ProcessVacuumAerateValvePulse,
    ProcessVacuumValveOpen,
    ProcessVacuumVaporTemperature,
    ProcessVacuumAutoDestinationIn,
    ProcessVacuumAutoDestinationOut,
    ProcessVacuumPowerPercent,
    ProcessVacuumRunning,
    ProcessRotationSet,
    ProcessRotationRunning,
    ProcessLiftSet,
    ProcessLiftActual,
    ProcessLiftLimit,
    ProcessGlobalStatusProcessTime,
    ProcessGlobalStatusRunId,
    ProcessGlobalStatusRunning,
    ProcessGlobalStatusOnHold,
    ProcessGlobalStatusFoamActive,
    ProcessGlobalStatusCurrentError,
    SettingsDisplayBrightness,
    SettingsDisplayUtcOffset,
    SettingsSoundsButtonTone,
    SettingsSoundsPlaySoundOnFinish,
    SettingsVacuumPressureHysteresis,
    SettingsVacuumAltitude,
    SettingsVacuumMaxPermPressure,
    SettingsVacuumMaxPumpOutput,
    SettingsVacuumVentOnFinish,
    SettingsRotationStopOnFinish,
    SettingsHeatingMaxTemperature,
    SettingsHeatingStopOnFinish,
    SettingsCoolingStopOnFinish,
    SettingsLiftDepthStop,
    SettingsLiftImmerseOnStart,
    SettingsLiftOutFlaskOnFinish,
    SettingsRotationStartOnStart,
    SettingsProgramEcoEnabled,
    SettingsProgramEcoActivationAfterMins,
    SettingsProgramEcoHeatingBathTemperature,
    SettingsProgramEcoCoolantTemperature,
    InfoControllerOperatingTimeHours,
    InfoControllerRunTotalRuns,
    InfoControllerRunManual,
    InfoControllerRunTimer,
    InfoControllerRunContinuous,
    InfoControllerRunSolvent,
    InfoControllerRunMethod,
    InfoControllerRunAutoDest,
    InfoControllerRunCloudDest,
    InfoControllerRunDrying,
    InfoControllerRunLeakTest,
    InfoControllerRunCalibration,
    InfoBathOperatingTimeHours,
    InfoBathHoursOver190c,
    InfoChillerOperatingTimeHours,
    InfoChillerPumpHours,
    InfoChillerCompressorHours,
    InfoChillerValveCounter,
    InfoRotavaporOperatingTimeHours,
    InfoRotavaporRotationHours,
    InfoRotavaporLiftMoves,
    InfoPumpOperatingTimeHours,
    InfoPumpModule1SwitchOn,
    InfoPumpModule1OverCurrent,
    InfoPumpModule1MaxCurrent,
    InfoPumpModule1MaxTemperature,
    InfoPumpModule2SwitchOn,
    InfoPumpModule2OverCurrent,
    InfoPumpModule2MaxCurrent,
    InfoPumpModule2MaxTemperature,
    InfoVacuboxOperatingTimeHours,
    InfoBathAttached,
    InfoChillerAttached,
    InfoRotavaporAttached,
    InfoPumpAttached,
    InfoVacuboxAttached,
}

impl RuntimeNode {
    pub const fn index(self) -> usize {
        self as usize
    }

    pub const fn endpoint(self) -> Endpoint {
        let index = self.index();
        if index < SETTINGS_NODE_OFFSET {
            Endpoint::Process
        } else if index < INFO_NODE_OFFSET {
            Endpoint::Settings
        } else {
            Endpoint::Info
        }
    }

    pub const fn freshness_ms(self) -> u32 {
        self.endpoint().freshness_ms()
    }

    pub fn contract(self) -> &'static RuntimeNodeContract {
        &RUNTIME_NODE_CONTRACTS[self.index()]
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RuntimeNodeContract {
    pub node: RuntimeNode,
    pub browse_name: &'static str,
    pub endpoint: Endpoint,
    pub value_kind: ValueKind,
    pub writable_node_id: Option<u16>,
}

const fn contract(
    node: RuntimeNode,
    browse_name: &'static str,
    value_kind: ValueKind,
    writable_node_id: Option<u16>,
) -> RuntimeNodeContract {
    RuntimeNodeContract {
        node,
        browse_name,
        endpoint: node.endpoint(),
        value_kind,
        writable_node_id,
    }
}

pub const RUNTIME_NODE_CONTRACTS: [RuntimeNodeContract; NODE_COUNT] = [
    contract(
        RuntimeNode::ProcessState,
        "Process.State",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::ProcessHeatingSet,
        "Process.Heating.Set",
        ValueKind::Float,
        Some(2001),
    ),
    contract(
        RuntimeNode::ProcessBathTemperature,
        "Process.Heating.Actual",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessHeatingRunning,
        "Process.Heating.Running",
        ValueKind::Boolean,
        Some(2003),
    ),
    contract(
        RuntimeNode::ProcessCoolingSet,
        "Process.Cooling.Set",
        ValueKind::Float,
        Some(2004),
    ),
    contract(
        RuntimeNode::ProcessCoolingActual,
        "Process.Cooling.Actual",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessCoolingRunning,
        "Process.Cooling.Running",
        ValueKind::Boolean,
        Some(2006),
    ),
    contract(
        RuntimeNode::ProcessVacuumSet,
        "Process.Vacuum.Set",
        ValueKind::Float,
        Some(2007),
    ),
    contract(
        RuntimeNode::ProcessRotationSpeed,
        "Process.Rotation.Actual",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessPressure,
        "Process.Vacuum.Pressure",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessVacuumAerateValveOpen,
        "Process.Vacuum.AerateValveOpen",
        ValueKind::Boolean,
        Some(2009),
    ),
    contract(
        RuntimeNode::ProcessVacuumAerateValvePulse,
        "Process.Vacuum.AerateValvePulse",
        ValueKind::Boolean,
        Some(2010),
    ),
    contract(
        RuntimeNode::ProcessVacuumValveOpen,
        "Process.Vacuum.ValveOpen",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::ProcessVacuumVaporTemperature,
        "Process.Vacuum.VaporTemperature",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessVacuumAutoDestinationIn,
        "Process.Vacuum.AutoDestinationIn",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessVacuumAutoDestinationOut,
        "Process.Vacuum.AutoDestinationOut",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessVacuumPowerPercent,
        "Process.Vacuum.PowerPercentActual",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessVacuumRunning,
        "Process.Vacuum.Running",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::ProcessRotationSet,
        "Process.Rotation.Set",
        ValueKind::Float,
        Some(2017),
    ),
    contract(
        RuntimeNode::ProcessRotationRunning,
        "Process.Rotation.Running",
        ValueKind::Boolean,
        Some(2019),
    ),
    contract(
        RuntimeNode::ProcessLiftSet,
        "Process.Lift.Set",
        ValueKind::Float,
        Some(2020),
    ),
    contract(
        RuntimeNode::ProcessLiftActual,
        "Process.Lift.Actual",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessLiftLimit,
        "Process.Lift.Limit",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::ProcessGlobalStatusProcessTime,
        "Process.GlobalStatus.ProcessTimeSeconds",
        ValueKind::UInt32,
        None,
    ),
    contract(
        RuntimeNode::ProcessGlobalStatusRunId,
        "Process.GlobalStatus.RunId",
        ValueKind::UInt32,
        None,
    ),
    contract(
        RuntimeNode::ProcessGlobalStatusRunning,
        "Process.GlobalStatus.Running",
        ValueKind::Boolean,
        Some(2030),
    ),
    contract(
        RuntimeNode::ProcessGlobalStatusOnHold,
        "Process.GlobalStatus.OnHold",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::ProcessGlobalStatusFoamActive,
        "Process.GlobalStatus.FoamActive",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::ProcessGlobalStatusCurrentError,
        "Process.GlobalStatus.CurrentError",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::SettingsDisplayBrightness,
        "Settings.Display.BrightnessPercent",
        ValueKind::Int32,
        Some(3018),
    ),
    contract(
        RuntimeNode::SettingsDisplayUtcOffset,
        "Settings.Display.UtcOffsetMinutes",
        ValueKind::Int32,
        Some(3019),
    ),
    contract(
        RuntimeNode::SettingsSoundsButtonTone,
        "Settings.Sounds.ButtonTone",
        ValueKind::Boolean,
        Some(3020),
    ),
    contract(
        RuntimeNode::SettingsSoundsPlaySoundOnFinish,
        "Settings.Sounds.PlaySoundOnFinish",
        ValueKind::Boolean,
        Some(3021),
    ),
    contract(
        RuntimeNode::SettingsVacuumPressureHysteresis,
        "Settings.Vacuum.PressureHysteresisMbar",
        ValueKind::Float,
        Some(3005),
    ),
    contract(
        RuntimeNode::SettingsVacuumAltitude,
        "Settings.Vacuum.AltitudeMeters",
        ValueKind::Float,
        Some(3006),
    ),
    contract(
        RuntimeNode::SettingsVacuumMaxPermPressure,
        "Settings.Vacuum.MaxPermPressureMbar",
        ValueKind::Float,
        Some(3001),
    ),
    contract(
        RuntimeNode::SettingsVacuumMaxPumpOutput,
        "Settings.Vacuum.MaxPumpOutputPercent",
        ValueKind::Int32,
        Some(3007),
    ),
    contract(
        RuntimeNode::SettingsVacuumVentOnFinish,
        "Settings.Vacuum.VentOnFinish",
        ValueKind::Boolean,
        Some(3008),
    ),
    contract(
        RuntimeNode::SettingsRotationStopOnFinish,
        "Settings.Rotation.StopRotationOnFinish",
        ValueKind::Boolean,
        Some(3009),
    ),
    contract(
        RuntimeNode::SettingsHeatingMaxTemperature,
        "Settings.Heating.MaxTemperatureC",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::SettingsHeatingStopOnFinish,
        "Settings.Heating.StopHeatingOnFinish",
        ValueKind::Boolean,
        Some(3010),
    ),
    contract(
        RuntimeNode::SettingsCoolingStopOnFinish,
        "Settings.Cooling.StopCoolingOnFinish",
        ValueKind::Boolean,
        Some(3011),
    ),
    contract(
        RuntimeNode::SettingsLiftDepthStop,
        "Settings.Lift.DepthStop",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::SettingsLiftImmerseOnStart,
        "Settings.Lift.ImmerseOnStart",
        ValueKind::Boolean,
        Some(3012),
    ),
    contract(
        RuntimeNode::SettingsLiftOutFlaskOnFinish,
        "Settings.Lift.LiftOutFlaskOnFinish",
        ValueKind::Boolean,
        Some(3013),
    ),
    contract(
        RuntimeNode::SettingsRotationStartOnStart,
        "Settings.Rotation.StartRotationOnStart",
        ValueKind::Boolean,
        Some(3004),
    ),
    contract(
        RuntimeNode::SettingsProgramEcoEnabled,
        "Settings.Program.Eco.Enabled",
        ValueKind::Boolean,
        Some(3014),
    ),
    contract(
        RuntimeNode::SettingsProgramEcoActivationAfterMins,
        "Settings.Program.Eco.ActivationAfterMins",
        ValueKind::Int32,
        Some(3015),
    ),
    contract(
        RuntimeNode::SettingsProgramEcoHeatingBathTemperature,
        "Settings.Program.Eco.HeatingBathTemperatureC",
        ValueKind::Float,
        Some(3016),
    ),
    contract(
        RuntimeNode::SettingsProgramEcoCoolantTemperature,
        "Settings.Program.Eco.CoolantTemperatureC",
        ValueKind::Float,
        Some(3017),
    ),
    contract(
        RuntimeNode::InfoControllerOperatingTimeHours,
        "Info.Controller.OperatingTimeHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunTotalRuns,
        "Info.Controller.RunCounters.TotalRuns",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunManual,
        "Info.Controller.RunCounters.Manual",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunTimer,
        "Info.Controller.RunCounters.Timer",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunContinuous,
        "Info.Controller.RunCounters.Continuous",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunSolvent,
        "Info.Controller.RunCounters.Solvent",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunMethod,
        "Info.Controller.RunCounters.Method",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunAutoDest,
        "Info.Controller.RunCounters.AutoDest",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunCloudDest,
        "Info.Controller.RunCounters.CloudDest",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunDrying,
        "Info.Controller.RunCounters.Drying",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunLeakTest,
        "Info.Controller.RunCounters.LeakTest",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoControllerRunCalibration,
        "Info.Controller.RunCounters.Calibration",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoBathOperatingTimeHours,
        "Info.Bath.OperatingTimeHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoBathHoursOver190c,
        "Info.Bath.HoursOver190C",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoChillerOperatingTimeHours,
        "Info.Chiller.OperatingTimeHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoChillerPumpHours,
        "Info.Chiller.PumpHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoChillerCompressorHours,
        "Info.Chiller.CompressorHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoChillerValveCounter,
        "Info.Chiller.ValveCounter",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoRotavaporOperatingTimeHours,
        "Info.Rotavapor.OperatingTimeHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoRotavaporRotationHours,
        "Info.Rotavapor.RotationHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoRotavaporLiftMoves,
        "Info.Rotavapor.LiftMoves",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpOperatingTimeHours,
        "Info.Pump.OperatingTimeHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule1SwitchOn,
        "Info.Pump.Module1.SwitchOn",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule1OverCurrent,
        "Info.Pump.Module1.OverCurrent",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule1MaxCurrent,
        "Info.Pump.Module1.MaxCurrentAmps",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule1MaxTemperature,
        "Info.Pump.Module1.MaxTemperatureC",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule2SwitchOn,
        "Info.Pump.Module2.SwitchOn",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule2OverCurrent,
        "Info.Pump.Module2.OverCurrent",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule2MaxCurrent,
        "Info.Pump.Module2.MaxCurrentAmps",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpModule2MaxTemperature,
        "Info.Pump.Module2.MaxTemperatureC",
        ValueKind::Float,
        None,
    ),
    contract(
        RuntimeNode::InfoVacuboxOperatingTimeHours,
        "Info.Vacubox.OperatingTimeHours",
        ValueKind::Int32,
        None,
    ),
    contract(
        RuntimeNode::InfoBathAttached,
        "Info.Bath.Attached",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::InfoChillerAttached,
        "Info.Chiller.Attached",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::InfoRotavaporAttached,
        "Info.Rotavapor.Attached",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::InfoPumpAttached,
        "Info.Pump.Attached",
        ValueKind::Boolean,
        None,
    ),
    contract(
        RuntimeNode::InfoVacuboxAttached,
        "Info.Vacubox.Attached",
        ValueKind::Boolean,
        None,
    ),
];

pub fn runtime_node_contracts() -> &'static [RuntimeNodeContract; NODE_COUNT] {
    &RUNTIME_NODE_CONTRACTS
}

pub fn runtime_node_contract_by_index(index: usize) -> Option<&'static RuntimeNodeContract> {
    RUNTIME_NODE_CONTRACTS.get(index)
}

impl RuntimeNodeContract {
    pub const fn access(self) -> Access {
        if self.writable_node_id.is_some() {
            Access::WritableNumericBoolean
        } else {
            Access::ReadOnly
        }
    }
}
