// Copyright 2026 Nicholas Salois.
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the repository root for the full license.

use crate::Endpoint;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WriteEndpoint {
    Process,
    Settings,
}

impl WriteEndpoint {
    pub const fn endpoint(self) -> Endpoint {
        match self {
            WriteEndpoint::Process => Endpoint::Process,
            WriteEndpoint::Settings => Endpoint::Settings,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WriteValueType {
    Boolean,
    Int32,
    Float,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WriteTarget {
    None,
    ProcessHeatingSet,
    ProcessHeatingRunning,
    ProcessCoolingSet,
    ProcessCoolingRunning,
    ProcessVacuumSet,
    ProcessVacuumAerateValveOpen,
    ProcessVacuumAerateValvePulse,
    ProcessRotationSet,
    ProcessRotationRunning,
    ProcessLiftSet,
    ProcessGlobalStatusRunning,
    SettingsDisplayBrightness,
    SettingsDisplayUtcOffset,
    SettingsSoundsButtonTone,
    SettingsSoundsPlaySoundOnFinish,
    SettingsVacuumPressureHysteresis,
    SettingsVacuumAltitude,
    SettingsVacuumMaxPermPressure,
    SettingsVacuumMaxPumpOutput,
    SettingsVacuumVentOnFinish,
    SettingsRotationStartRotationOnStart,
    SettingsRotationStopRotationOnFinish,
    SettingsHeatingStopHeatingOnFinish,
    SettingsCoolingStopCoolingOnFinish,
    SettingsLiftImmerseOnStart,
    SettingsLiftOutFlaskOnFinish,
    SettingsProgramEcoEnabled,
    SettingsProgramEcoActivationAfterMins,
    SettingsProgramEcoHeatingBathTemperature,
    SettingsProgramEcoCoolantTemperature,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct WriteSpec {
    pub target: WriteTarget,
    pub endpoint: WriteEndpoint,
    pub node_id: u16,
    pub browse_name: &'static str,
    pub object_key: &'static str,
    pub child_key: Option<&'static str>,
    pub value_key: &'static str,
    pub value_type: WriteValueType,
    pub min_raw: i32,
    pub max_raw: i32,
    pub multiple_raw: i32,
    pub scale: i32,
}

pub const WRITE_SPECS: &[WriteSpec] = &[
    WriteSpec {
        target: WriteTarget::ProcessHeatingSet,
        endpoint: WriteEndpoint::Process,
        node_id: 2001,
        browse_name: "Process.Heating.Set",
        object_key: "heating",
        child_key: None,
        value_key: "set",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 220_000,
        multiple_raw: 0,
        scale: 1_000,
    },
    WriteSpec {
        target: WriteTarget::ProcessHeatingRunning,
        endpoint: WriteEndpoint::Process,
        node_id: 2003,
        browse_name: "Process.Heating.Running",
        object_key: "heating",
        child_key: None,
        value_key: "running",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessCoolingSet,
        endpoint: WriteEndpoint::Process,
        node_id: 2004,
        browse_name: "Process.Cooling.Set",
        object_key: "cooling",
        child_key: None,
        value_key: "set",
        value_type: WriteValueType::Float,
        min_raw: -10_000,
        max_raw: 25_000,
        multiple_raw: 0,
        scale: 1_000,
    },
    WriteSpec {
        target: WriteTarget::ProcessCoolingRunning,
        endpoint: WriteEndpoint::Process,
        node_id: 2006,
        browse_name: "Process.Cooling.Running",
        object_key: "cooling",
        child_key: None,
        value_key: "running",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessVacuumSet,
        endpoint: WriteEndpoint::Process,
        node_id: 2007,
        browse_name: "Process.Vacuum.Set",
        object_key: "vacuum",
        child_key: None,
        value_key: "set",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 1_300,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessVacuumAerateValveOpen,
        endpoint: WriteEndpoint::Process,
        node_id: 2009,
        browse_name: "Process.Vacuum.AerateValveOpen",
        object_key: "vacuum",
        child_key: None,
        value_key: "aerateValveOpen",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessVacuumAerateValvePulse,
        endpoint: WriteEndpoint::Process,
        node_id: 2010,
        browse_name: "Process.Vacuum.AerateValvePulse",
        object_key: "vacuum",
        child_key: None,
        value_key: "aerateValvePulse",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessRotationSet,
        endpoint: WriteEndpoint::Process,
        node_id: 2017,
        browse_name: "Process.Rotation.Set",
        object_key: "rotation",
        child_key: None,
        value_key: "set",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 280,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessRotationRunning,
        endpoint: WriteEndpoint::Process,
        node_id: 2019,
        browse_name: "Process.Rotation.Running",
        object_key: "rotation",
        child_key: None,
        value_key: "running",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::ProcessLiftSet,
        endpoint: WriteEndpoint::Process,
        node_id: 2020,
        browse_name: "Process.Lift.Set",
        object_key: "lift",
        child_key: None,
        value_key: "set",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 220_000,
        multiple_raw: 220_000,
        scale: 1_000,
    },
    WriteSpec {
        target: WriteTarget::ProcessGlobalStatusRunning,
        endpoint: WriteEndpoint::Process,
        node_id: 2030,
        browse_name: "Process.GlobalStatus.Running",
        object_key: "globalStatus",
        child_key: None,
        value_key: "running",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsDisplayBrightness,
        endpoint: WriteEndpoint::Settings,
        node_id: 3018,
        browse_name: "Settings.Display.BrightnessPercent",
        object_key: "display",
        child_key: None,
        value_key: "brightness",
        value_type: WriteValueType::Int32,
        min_raw: 0,
        max_raw: 100,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsDisplayUtcOffset,
        endpoint: WriteEndpoint::Settings,
        node_id: 3019,
        browse_name: "Settings.Display.UtcOffsetMinutes",
        object_key: "display",
        child_key: None,
        value_key: "utcOffset",
        value_type: WriteValueType::Int32,
        min_raw: -720,
        max_raw: 840,
        multiple_raw: 30,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsSoundsButtonTone,
        endpoint: WriteEndpoint::Settings,
        node_id: 3020,
        browse_name: "Settings.Sounds.ButtonTone",
        object_key: "sounds",
        child_key: None,
        value_key: "buttonTone",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsSoundsPlaySoundOnFinish,
        endpoint: WriteEndpoint::Settings,
        node_id: 3021,
        browse_name: "Settings.Sounds.PlaySoundOnFinish",
        object_key: "sounds",
        child_key: None,
        value_key: "playSoundOnFinish",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsVacuumPressureHysteresis,
        endpoint: WriteEndpoint::Settings,
        node_id: 3005,
        browse_name: "Settings.Vacuum.PressureHysteresisMbar",
        object_key: "vacuum",
        child_key: None,
        value_key: "pressureHysteresis",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 200,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsVacuumAltitude,
        endpoint: WriteEndpoint::Settings,
        node_id: 3006,
        browse_name: "Settings.Vacuum.AltitudeMeters",
        object_key: "vacuum",
        child_key: None,
        value_key: "altitude",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 4_000,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsVacuumMaxPermPressure,
        endpoint: WriteEndpoint::Settings,
        node_id: 3001,
        browse_name: "Settings.Vacuum.MaxPermPressureMbar",
        object_key: "vacuum",
        child_key: None,
        value_key: "maxPermPressure",
        value_type: WriteValueType::Float,
        min_raw: 0,
        max_raw: 1_300,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsVacuumMaxPumpOutput,
        endpoint: WriteEndpoint::Settings,
        node_id: 3007,
        browse_name: "Settings.Vacuum.MaxPumpOutputPercent",
        object_key: "vacuum",
        child_key: None,
        value_key: "maxPumpOutput",
        value_type: WriteValueType::Int32,
        min_raw: 0,
        max_raw: 100,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsVacuumVentOnFinish,
        endpoint: WriteEndpoint::Settings,
        node_id: 3008,
        browse_name: "Settings.Vacuum.VentOnFinish",
        object_key: "vacuum",
        child_key: None,
        value_key: "ventOnFinish",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsRotationStartRotationOnStart,
        endpoint: WriteEndpoint::Settings,
        node_id: 3004,
        browse_name: "Settings.Rotation.StartRotationOnStart",
        object_key: "rotation",
        child_key: None,
        value_key: "startRotationOnStart",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsRotationStopRotationOnFinish,
        endpoint: WriteEndpoint::Settings,
        node_id: 3009,
        browse_name: "Settings.Rotation.StopRotationOnFinish",
        object_key: "rotation",
        child_key: None,
        value_key: "stopRotationOnFinish",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsHeatingStopHeatingOnFinish,
        endpoint: WriteEndpoint::Settings,
        node_id: 3010,
        browse_name: "Settings.Heating.StopHeatingOnFinish",
        object_key: "heating",
        child_key: None,
        value_key: "stopHeatingOnFinish",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsCoolingStopCoolingOnFinish,
        endpoint: WriteEndpoint::Settings,
        node_id: 3011,
        browse_name: "Settings.Cooling.StopCoolingOnFinish",
        object_key: "cooling",
        child_key: None,
        value_key: "stopCoolingOnFinish",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsLiftImmerseOnStart,
        endpoint: WriteEndpoint::Settings,
        node_id: 3012,
        browse_name: "Settings.Lift.ImmerseOnStart",
        object_key: "lift",
        child_key: None,
        value_key: "immerseOnStart",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsLiftOutFlaskOnFinish,
        endpoint: WriteEndpoint::Settings,
        node_id: 3013,
        browse_name: "Settings.Lift.LiftOutFlaskOnFinish",
        object_key: "lift",
        child_key: None,
        value_key: "liftOutFlaskOnFinish",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsProgramEcoEnabled,
        endpoint: WriteEndpoint::Settings,
        node_id: 3014,
        browse_name: "Settings.Program.Eco.Enabled",
        object_key: "program",
        child_key: Some("eco"),
        value_key: "isEnabled",
        value_type: WriteValueType::Boolean,
        min_raw: 0,
        max_raw: 1,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsProgramEcoActivationAfterMins,
        endpoint: WriteEndpoint::Settings,
        node_id: 3015,
        browse_name: "Settings.Program.Eco.ActivationAfterMins",
        object_key: "program",
        child_key: Some("eco"),
        value_key: "activationAfterMins",
        value_type: WriteValueType::Int32,
        min_raw: 5,
        max_raw: 100,
        multiple_raw: 0,
        scale: 1,
    },
    WriteSpec {
        target: WriteTarget::SettingsProgramEcoHeatingBathTemperature,
        endpoint: WriteEndpoint::Settings,
        node_id: 3016,
        browse_name: "Settings.Program.Eco.HeatingBathTemperatureC",
        object_key: "program",
        child_key: Some("eco"),
        value_key: "heatingBathTemperature",
        value_type: WriteValueType::Float,
        min_raw: 3_000,
        max_raw: 200_000,
        multiple_raw: 0,
        scale: 1_000,
    },
    WriteSpec {
        target: WriteTarget::SettingsProgramEcoCoolantTemperature,
        endpoint: WriteEndpoint::Settings,
        node_id: 3017,
        browse_name: "Settings.Program.Eco.CoolantTemperatureC",
        object_key: "program",
        child_key: Some("eco"),
        value_key: "coolantTemperature",
        value_type: WriteValueType::Float,
        min_raw: 3_000,
        max_raw: 50_000,
        multiple_raw: 0,
        scale: 1_000,
    },
];
